<%@ Page Title="" Language="C#" MasterPageFile="~/Project/documentation/documentMaster.master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
        <link href="../../css/documentationCSS.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <section>
        <h1> Album Details Page </h1>
        <p>
            The details page is displayed when the user selects an album from search results. I use the lastfm API<b>"album.info" method</b> to get a JSON
                    response, which can be parsed to display the results. I display the album name, cover picture, artist name, release date, 
                    number of listeners, playcount, all the tracks in the album and the buy links for the album.
            <br />
            <br />
            All the tracks in the album are listed. For each track, I show the track name, track duration and track artist. 
            The track artist can be clicked, and the user will be navigated to the artist details page.
            <br /><br />
            The buy links are generated by using the method <b>"album.getbuylinks"</b> from lastfm API. For each buy-link, I display the supplier-icon,
            supplier name, price and a link. When user clicks on "buy now", it redirects them to the suppliers page where they can buy the album.

                    </p>

        <h2>Snapshot : </h2>
        <img src="../../images/albumDetail.PNG" />

         <br />
        <h2>Source Files :</h2>
        <p>
             <a href="../../fileview/Default.aspx?~/Project/albumInfo.aspx" target="_blank">ASPX Source</a><br />
        </p>
       
    </section>
</asp:Content>

