<%@ Page Title="" Language="C#" MasterPageFile="~/Project/documentation/documentMaster.master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <link href="../../css/documentationCSS.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <section>
        <h1>Events Page</h1>
        <p>
            This functionality shows the event details for an artist name entered by the user. A list of events is displayed as result
            This list is generated by JSON response of <b>"artist.getevents" method</b> from last fm API.
            <br />
            <br />
            For each event, I display the event title, artist name, date/timing of the event, attendance, event website, 
            venue name, address, phone number.

        </p>
        <br />
        <h2>Snapshot :</h2>
        <img src="../../images/eventResult.PNG" />
        <br />
        <h2>Source Files :</h2>
        <p>
            <a href="../../fileview/Default.aspx?~/Project/events.aspx" target="_blank">ASPX Source</a><br />

        </p>

    </section>
</asp:Content>

